"""add phone number

Revision ID: 785ae424bd26
Revises: 870846cde737
Create Date: 2023-06-23 12:15:47.681078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785ae424bd26'
down_revision = '870846cde737'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
